server:
    port: 4000

logging:
    level:
        root: warn

spring:
    main:
        banner-mode: "off"

#    jmx:
#        enabled: false

    application:
        name: IS-TP6-Back

    datasource:
        url: jdbc:postgresql://dpg-crh2e9tsvqrc73878190-a.oregon-postgres.render.com/tango_app_db
        username: admin
        password: ${RENDER_DB_PASSWORD}

    jpa:
        open-in-view: false

        hibernate:
            naming:
                # StandardImpl is used in order to not transform the attributes and tables from CamelCase to snake_case
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true

    mail:
        host: smtp.gmail.com
        port: 465
        username: noreply.tangoapp@gmail.com
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true
                    starttls:
                        enable: true
                        required: true

# Project specific configurations
firebase-storage:
    base-url: https://firebasestorage.googleapis.com/v0/b/is-tp6-firebase-storage.appspot.com/o/
    storage-bucket-url: is-tp6-firebase-storage.appspot.com

frontend:
    base-url: http://localhost:5173